apiVersion: v1
kind: Service
metadata:
  name: rag-api-service
  namespace: rag-app
  labels:
    app: rag-api
spec:
  selector:
    app: rag-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort